class  Appimageassets {
  static const rootimage = "assets/images";
  static const rootlotte = "assets/lotte";

  static const String logo  ="$rootimage/Logo.png";
  static const String ALG ="$rootimage/ALG.png";
  static const String en ="$rootimage/EN.jpeg";

  static const String test2 ="$rootimage/silaaty_desktop.png";
  static const String avater ="$rootimage/Avatar.jpg";


  static const String loading = "$rootlotte/loading1.json";  
  static const String nodata = "$rootlotte/nodata.json";
  static const String offline = "$rootlotte/offline.json";
  static const String server = "$rootlotte/server.json";

}